# Generated by Django 4.1.6 on 2023-02-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default='2023-02-15'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default='2023-02-15'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('u', 'Not started yet'), ('o', 'Ongoing'), ('f', 'Finished'), ('fail', 'Deadline')], max_length=10, verbose_name='Task status'),
        ),
    ]
